<?xml version= "1.0" ?>
<?xml-stylesheet type="text/xsl" href= "bookstore.xsl" ?>
<!DOCTYPE bookstore[
<!ELEMENT bookstore (book*)>
<!ELEMENT book (title,author,isbn,publisher,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<bookstore>
<book>
<title>Book1</title>
<author>author1</author>
<isbn>isbn1</isbn>
<publisher>publisher1</publisher>
<price>100</price>
</book>
<book>
<title>Book2</title>
<author>author1</author>
<isbn>isbn1</isbn>
<publisher>publisher1</publisher>
<price>200</price>
</book>
<book>
<title>Book3</title>
<author>author1</author>
<isbn>isbn1</isbn>
<publisher>publisher1</publisher>
<price>300</price>
</book>
</bookstore>
